const data={
    product:[
        {
            _id:'1',
            name:'nike',
            category:'shirts',
            images:'/images/product-1.png',
            price:120,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Adids',
            category:'shirts',
            images:'/images/product-1.png',
            price:110,
            brand:'Nike',
            rating:4.5,
            numReviews:11,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'nike',
            category:'shirts',
            images:'/images/p-3.png',
            price:150,
            brand:'Nike',
            rating:4.5,
            numReviews:15,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'nike',
            category:'pans',
            images:'/images/product-1.png',
            price:80,
            brand:'Nike',
            rating:4.5,
            numReviews:18,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Adidas',
            category:'shirts',
            images:'/images/p-2.png',
            price:100,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ],
};
export default data ;